set(ARDUINO_MEGA_PROTOCOL "wiring")
set(ARDUINO_MEGA_BOARD "mega")
set(ARDUINO_MEGA_MCU "atmega2560")
set(ARDUINO_MEGA_FCPU "16000000")
set(ARDUINO_MEGA_UPLOAD_SPEED "115200")
set(ARDUINO_MEGA_PORT "/dev/ttyUSB0")
set(ARDUINO_MEGA_ROOT "$ENV{HOME}/arduino-1.6.9")
set(CMAKE_C_COMPILER "${ARDUINO_MEGA_ROOT}/hardware/tools/avr/bin/avr-gcc")
set(CMAKE_CXX_COMPILER "${ARDUINO_MEGA_ROOT}/hardware/tools/avr/bin/avr-g++")
set(ARDUINO_MEGA_OBJCOPY "${ARDUINO_MEGA_ROOT}/hardware/tools/avr/bin/avr-objcopy")
set(ARDUINO_MEGA_AVRDUDE "${ARDUINO_MEGA_ROOT}/hardware/tools/avr/bin/avrdude")
include(${CMAKE_SOURCE_DIR}/scripts/libarduino_mega.cmake)
